use std::{
    env,
    fs::{self, File},
    io::{self, Write},
    path::{Path, PathBuf},
};

#[path = "src/app_metadata.rs"]
mod app_metadata;

fn main() {
    println!("cargo::rerun-if-changed=migrations");
    println!("cargo::rerun-if-changed=src/app_metadata.rs");
    println!("cargo::rerun-if-changed=assets/app-icons/phanerite.ico");

    if let Err(error) = generate_migrations() {
        panic!("failed to generate migrations: {error}");
    }

    // Build scripts run on the host; inspect the target so cross-compilation
    // also embeds the resources.
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        compile_windows_resources().expect("failed to compile Windows application resources");
    }
}

fn compile_windows_resources() -> io::Result<()> {
    let icon = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap())
        .join("assets/app-icons/phanerite.ico");
    let icon = icon.to_string_lossy().replace('\\', "\\\\");
    let version = env::var("CARGO_PKG_VERSION").unwrap();
    let file_version = format!(
        "{},{},{},0",
        env::var("CARGO_PKG_VERSION_MAJOR").unwrap(),
        env::var("CARGO_PKG_VERSION_MINOR").unwrap(),
        env::var("CARGO_PKG_VERSION_PATCH").unwrap(),
    );
    let app_name = app_metadata::APP_NAME;
    let app_title = app_metadata::APP_WINDOW_TITLE;
    let app_id = app_metadata::APP_ID;
    // GPUI's Windows backend loads the executable's icon with resource ID 1.
    let resources = format!(
        r#"1 ICON "{icon}"

1 VERSIONINFO
FILEVERSION {file_version}
PRODUCTVERSION {file_version}
FILEFLAGSMASK 0x3fL
FILEFLAGS 0x0L
FILEOS 0x40004L
FILETYPE 0x1L
FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "FileDescription", "{app_title}\0"
            VALUE "FileVersion", "{version}\0"
            VALUE "ProductName", "{app_name}\0"
            VALUE "ProductVersion", "{version}\0"
            VALUE "InternalName", "{app_id}\0"
            VALUE "OriginalFilename", "phanerite.exe\0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1200
    END
END
"#,
    );
    let path = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("phanerite.rc");
    fs::write(&path, resources)?;
    embed_resource::compile_for_everything(&path, embed_resource::NONE)
        .manifest_required()
        .map_err(io::Error::other)
}

fn generate_migrations() -> io::Result<()> {
    let migration_dir = Path::new("migrations");
    let mut migrations = Vec::new();

    for entry in fs::read_dir(migration_dir)? {
        let entry = entry?;
        if !entry.file_type()?.is_file() {
            println!(
                "cargo::warning={} is not a migration file",
                entry.path().display()
            );
            continue;
        }

        let path = entry.path();
        let ext = path.extension().and_then(|extension| extension.to_str());

        // Markdown documents are intentionally ignored
        if ext == Some("md") {
            continue;
        }

        if ext != Some("sql") {
            println!(
                "cargo::warning={} does not have a .sql extension",
                path.display()
            );
            continue;
        }

        migrations.push(parse_filename(&path)?);
    }

    migrations.sort_by_key(|migration| migration.id);
    for pair in migrations.windows(2) {
        if pair[0].id == pair[1].id {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("duplicate migration id: {}", pair[0].id),
            ));
        }
    }

    let output_path =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set")).join("migration_scripts.rs");
    let mut output = File::create(output_path)?;

    writeln!(
        output,
        "// Generated by build.rs. Do not edit this file manually."
    )?;
    writeln!(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]")?;
    writeln!(output, "pub struct Migration {{")?;
    writeln!(output, "    pub id: u16,")?;
    writeln!(output, "    pub slug: &'static str,")?;
    writeln!(output, "    pub sql: &'static str,")?;
    writeln!(output, "}}")?;
    writeln!(output, "pub const ALL: &[Migration] = &[")?;

    for migration in &migrations {
        let sql = fs::read_to_string(&migration.path)?;
        writeln!(
            output,
            "    Migration {{ id: {}, slug: {:?}, sql: r##\"{}\"## }},",
            migration.id, migration.slug, sql
        )?;
    }

    writeln!(output, "];")?;
    Ok(())
}

struct Migration {
    id: u16,
    slug: String,
    path: PathBuf,
}

fn parse_filename(path: &Path) -> io::Result<Migration> {
    let filename = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "migration filename is not valid Unicode: {}",
                    path.display()
                ),
            )
        })?;
    let stem = filename.strip_suffix(".sql").unwrap();
    let separator = stem.find(['-', '_']).ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("migration must be named <number>-<slug>.sql: {filename}"),
        )
    })?;
    let (id, slug) = stem.split_at(separator);
    let slug = &slug[1..];
    let id = id.parse::<u16>().map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("invalid migration id in {filename}: {error}"),
        )
    })?;
    if slug.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("migration slug cannot be empty: {filename}"),
        ));
    }

    Ok(Migration {
        id,
        slug: slug.to_string(),
        path: path.to_path_buf(),
    })
}
