use std::{
    env,
    fs::{self, File},
    io::{self, Write},
    path::{Path, PathBuf},
};

fn main() {
    println!("cargo::rerun-if-changed=migrations");

    if let Err(error) = generate_migrations() {
        panic!("failed to generate migrations: {error}");
    }
}

fn generate_migrations() -> io::Result<()> {
    let migration_dir = Path::new("migrations");
    let mut migrations = Vec::new();

    for entry in fs::read_dir(migration_dir)? {
        let entry = entry?;
        if !entry.file_type()?.is_file() {
            println!(
                "cargo::warning={} is not a migration file",
                entry.path().display()
            );
            continue;
        }

        let path = entry.path();
        let ext = path.extension().and_then(|extension| extension.to_str());

        // Markdown documents are intentionally ignored
        if ext == Some("md") {
            continue;
        }

        if ext != Some("sql") {
            println!(
                "cargo::warning={} does not have a .sql extension",
                path.display()
            );
            continue;
        }

        migrations.push(parse_filename(&path)?);
    }

    migrations.sort_by_key(|migration| migration.id);
    for pair in migrations.windows(2) {
        if pair[0].id == pair[1].id {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("duplicate migration id: {}", pair[0].id),
            ));
        }
    }

    let output_path =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set")).join("migration_scripts.rs");
    let mut output = File::create(output_path)?;

    writeln!(
        output,
        "// Generated by build.rs. Do not edit this file manually."
    )?;
    writeln!(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]")?;
    writeln!(output, "pub struct Migration {{")?;
    writeln!(output, "    pub id: u16,")?;
    writeln!(output, "    pub slug: &'static str,")?;
    writeln!(output, "    pub sql: &'static str,")?;
    writeln!(output, "}}")?;
    writeln!(output, "pub const ALL: &[Migration] = &[")?;

    for migration in &migrations {
        let sql = fs::read_to_string(&migration.path)?;
        writeln!(
            output,
            "    Migration {{ id: {}, slug: {:?}, sql: r##\"{}\"## }},",
            migration.id, migration.slug, sql
        )?;
    }

    writeln!(output, "];")?;
    Ok(())
}

struct Migration {
    id: u16,
    slug: String,
    path: PathBuf,
}

fn parse_filename(path: &Path) -> io::Result<Migration> {
    let filename = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "migration filename is not valid Unicode: {}",
                    path.display()
                ),
            )
        })?;
    let stem = filename.strip_suffix(".sql").unwrap();
    let separator = stem.find(['-', '_']).ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("migration must be named <number>-<slug>.sql: {filename}"),
        )
    })?;
    let (id, slug) = stem.split_at(separator);
    let slug = &slug[1..];
    let id = id.parse::<u16>().map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("invalid migration id in {filename}: {error}"),
        )
    })?;
    if slug.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("migration slug cannot be empty: {filename}"),
        ));
    }

    Ok(Migration {
        id,
        slug: slug.to_string(),
        path: path.to_path_buf(),
    })
}
