[package]
name = "phanerite"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "phanerite"
path = "src/main.rs"

[[example]]
name = "gallery"
path = "examples/gallery.rs"
required-features = ["gallery"]

[features]
default = ["seed"]
seed = []
gallery = ["seed"]

[dependencies]
phanerite-core = { path = "../phanerite-core" }
gpui = { git = "https://github.com/zed-industries/zed", features = ["wayland", "x11"] }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = [
  "font-kit",
  "wayland",
  "x11",
] }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "c6ffd3e166abb43bff8845f0aa61711adb128dcf" }
gpui-base = { git = "https://github.com/longbridge/gpui-component", rev = "c6ffd3e166abb43bff8845f0aa61711adb128dcf" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "c6ffd3e166abb43bff8845f0aa61711adb128dcf" }
anyhow = "1.0"
chrono.workspace = true
rust-embed = "8.12.0"
smallvec = "1.15.2"
zstd = "0.13.3"
dirs = "6.0.0"

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", features = ["test-support"] }
tempfile = "3"
