[package]
name = "phanerite-core"
version = "0.1.0"
edition = "2024"

[features]
tokio = ["dep:tokio"]
compio = ["dep:compio"]
reqwest = ["dep:reqwest", "tokio"]
nyquest = ["dep:nyquest"]

[dependencies]
tokio = { version = "1", features = ["fs", "io-util", "sync"], optional = true }
compio = { version = "0.19", features = ["io", "fs"], optional = true }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"], optional = true }
nyquest = { version = "0.4", features = ["async"], optional = true }
