[package]
name = "phanerite-core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5"
async-fs = "2.2"
async-lock = "3.4"
async-process = "2.5"
blake3 = { version = "1.8", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
event-listener = "5.4"
futures = "0.3"
hex = "0.4"
nyquest = { version = "0.4", features = ["async", "async-stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.11"
tracing = "0.1"
uuid = { version = "1.24", features = ["v7"] }

[dev-dependencies]
nyquest-backend-curl = { version = "0.4", features = ["async", "async-stream"] }
nyquest-preset = { version = "0.4", feature = ["async", "async-stream"] }
nyquest-backend-winrt = { version = "0.4", features = ["async", "async-stream"] }
smol = "2.0"
tracing-subscriber = "0.3"
